
# Site settings
title: Jarvis Wong
name: Jarvis Wong
email: wangxiao16@std.uestc.edu.cn
description: >
   Computer Science
baseurl: ""
url: "https://Jarviswx.github.io/"
github_username:  Jarviswx
disqus_baseurl: "https://Jarviswx.github.io/"
disqus_shortname: https-Jarviswx-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Jarviswx"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: Jarviswx
    url: https://github.com/Jarviswx
    desc: Fork me on GitHub
    share: false

